USE [master]
GO

/****** Object:  Database [FitnessClub]    Script Date: 17.03.2023 7:04:44 ******/
CREATE DATABASE [FitnessClub]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FitnessClub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FitnessClub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FitnessClub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FitnessClub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FitnessClub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FitnessClub] SET ARITHABORT OFF 
GO

ALTER DATABASE [FitnessClub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FitnessClub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FitnessClub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FitnessClub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FitnessClub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FitnessClub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FitnessClub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FitnessClub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FitnessClub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FitnessClub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FitnessClub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FitnessClub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FitnessClub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FitnessClub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FitnessClub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FitnessClub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FitnessClub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FitnessClub] SET RECOVERY FULL 
GO

ALTER DATABASE [FitnessClub] SET  MULTI_USER 
GO

ALTER DATABASE [FitnessClub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FitnessClub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FitnessClub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FitnessClub] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FitnessClub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FitnessClub] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FitnessClub] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FitnessClub] SET  READ_WRITE 
GO


