//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClubErmakov.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
            this.Service = new HashSet<Service>();
        }
    
        public int IdClient { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Patronimic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdTag { get; set; }
        public string GenderCode { get; set; }
        public byte[] PhotoPath { get; set; }
        public Nullable<int> IdUser { get; set; }
        public System.DateTime BirthdayDate { get; set; }
    
        public virtual GenderCode GenderCode1 { get; set; }
        public virtual TagOfClient TagOfClient { get; set; }
        public virtual UserAuth UserAuth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
